services:
  - type: web
    name: standoff-arena-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npx prisma db push --accept-data-loss && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: standoff-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: standoff-redis
          property: connectionString

  - type: keyvalue
    name: standoff-redis
    plan: free
    ipAllowList: []

databases:
  - name: standoff-db
    plan: free
    databaseName: standoff_arena
    user: arena_admin
